export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_ERROR = 'FETCH_IMAGES_ERROR';

export const UPDATE_LIKES = 'UPDATE_LIKES';
export const IMAGES_SET_STATE = 'IMAGES_SET_STATE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';